#!/usr/bin/env python
# encoding: utf-8
"""
@Company：华中科技大学电气学院
@version: V1.0
@author: Victor
@contact: 1650996069@qq.com  2018--2020
@software: PyCharm
@file: SelectionSort.py
@time: 2019/2/20 10:22
@Desc：选择排序法：反复从未排序的数列当中选取最小的元素，加入到另外一组数列中，最后的结果为已排序的数列
"""
import datetime
startime = datetime.datetime.now()

def showdata(data):
    for i in range(len(data)):
        print('%5d' %data[i],end=' ')



def selectsort(data):
    for i in range(len(data)-1):
        for j in range(i+1,len(data)):
            if data[i]>data[j]:
                data[i],data[j] = data[j],data[i]
        #print(" ")
    return data




data = [12, 45, 2, 67, 34, 6, 90, 14]

print("原始数据：")
showdata(data)
print(' ')

print("排序后的数据：")
data = selectsort(data)
showdata(data)

print(" ")
endtime = datetime.datetime.now()
print("用时：",(endtime-startime).microseconds)
